Web-Developer-VEC/VEC_Web_Engine

- Frontend/package-lock.json
- Frontend/package.json
- Frontend/src/Components/Events.jsx
- Frontend/src/Components/ImgSld.jsx
- Frontend/src/Components/Tracker.jsx
- Frontend/src/Components/announcements.css
- Frontend/src/Components/announcements.jsx
> Landing page

- Frontend/src/Components/Nav_Bar_Comp/ProudAlumni.jsx
> intregrating proudalumni with db

- Frontend/src/Components/naac.css
- Frontend/src/Components/naac.jsx
- Frontend/src/Components/nirf.css
- Frontend/src/Components/nirf.jsx
> NAAC and NIRF

- Frontend/src/Components/NBA_F.css
- Frontend/src/Components/NBA_F.jsx
- Frontend/src/Components/Nav_Bar_Comp/PlacementDetails.css
- Frontend/src/Components/Nav_Bar_Comp/PlacementDetails.jsx
- Frontend/src/Components/Nav_Bar_Comp/PlacementTeam.jsx
- Frontend/src/Components/announcements.css
- Frontend/src/Components/announcements.jsx
- Frontend/src/Components/structure/sections/VisionMission.jsx
nba announcement placementDetails integrated with DB and loading page completed
> nba announcement placementDetails

- Frontend/src/Components/NBA_F.jsx
- Frontend/src/Components/Nav_Bar_Comp/Forms.css
- Frontend/src/Components/Nav_Bar_Comp/Regulation.css
- Frontend/src/Components/Nav_Bar_Comp/Regulation.jsx
- Frontend/src/Components/Nav_Bar_Comp/Syllabi.css
- Frontend/src/Components/Nav_Bar_Comp/Syllabus.jsx
- Frontend/src/Components/Nav_Bar_Comp/forms.jsx
- Frontend/src/Components/naac.css
- Frontend/src/Components/naac.jsx
- Frontend/src/Components/nirf.css
- Frontend/src/Components/nirf.jsx
nba, naac, exam section completed with DB integration and loading screen
> nba, naac, exam section completed

- Frontend/src/Components/structure/sections/Faculties.jsx
- Frontend/src/Components/structure/sections/Faculties.module.css
- Frontend/src/Components/structure/sections/ImageCard.jsx
> Faculties page updated for HOD

- Frontend/src/Components/Second_Nav_Bar/Alumni.css
- Frontend/src/Components/Second_Nav_Bar/Alumni.jsx
> alumni page

- Frontend/src/Components/Top_Nav_Bar/About Us/Management.css
- Frontend/src/Components/Top_Nav_Bar/About Us/Management.jsx
> management  tinkering

- Frontend/src/Components/Second_Nav_Bar/Alumni.css
- Frontend/src/Components/Second_Nav_Bar/Alumni.jsx
- Frontend/src/Components/Second_Nav_Bar/InClub.css
- Frontend/src/Components/Second_Nav_Bar/InCub.jsx
- Frontend/src/Components/Second_Nav_Bar/NBA_F.css
- Frontend/src/Components/Second_Nav_Bar/NBA_F.jsx
- Frontend/src/Components/Second_Nav_Bar/NSS/NSSCoordinatiors.jsx
- Frontend/src/Components/Second_Nav_Bar/NSS/NSSManuel.css
- Frontend/src/Components/Second_Nav_Bar/naac.css
- Frontend/src/Components/Second_Nav_Bar/naac.jsx
- Frontend/src/Components/Second_Nav_Bar/nirf.css
- Frontend/src/Components/Second_Nav_Bar/nirf.jsx
> second bar changes

- Backend/Main/controllers/secondnavbarController.js
- Backend/Main/routes/secondnavbar.js
- Frontend/src/App.js
- Frontend/src/Components/Second_Nav_Bar/IQAC.jsx
- Frontend/src/Components/Second_Nav_Bar/NBA_F.jsx
- Frontend/src/Components/Second_Nav_Bar/naac.jsx
- Frontend/src/Components/Second_Nav_Bar/nirf.jsx
NBA,NAAC,NIRF,IQUA integration completed
> Newgen Accordination integration

- Frontend/src/Components/Landing Comp/ImgSld.jsx
- Frontend/src/Components/Top_Nav_Bar/About Us/AbtUs.jsx
- Frontend/src/Components/Top_Nav_Bar/About Us/Management.jsx
- Frontend/src/Components/Top_Nav_Bar/About Us/Trust.jsx
- Frontend/src/Components/Top_Nav_Bar/About Us/collegevisionmission.jsx
- Frontend/src/Components/Top_Nav_Bar/Administration/Organization_chart.jsx
Frontend Image linked with s3 for localvec.duckdns.org
> Frontend Image linked with s3

- Frontend/src/Components/Second_Nav_Bar/Grievences.css
- Frontend/src/Components/Second_Nav_Bar/Grievences.jsx
> help desk(greveinces)

- Frontend/src/Components/Second_Nav_Bar/InCub.jsx
- Frontend/src/Components/Second_Nav_Bar/Incub.css
- Frontend/src/Components/Top_Nav_Bar/About Us/Management.jsx
- Frontend/src/Components/Top_Nav_Bar/About Us/collegevisionmission.jsx
- Frontend/src/Components/Top_Nav_Bar/Academics/sections/CurriculamPage.jsx
- Frontend/src/Components/Top_Nav_Bar/Academics/sections/CurriculumPage.css
- Frontend/src/Components/Top_Nav_Bar/Administration/Executive commitee.jsx
Incubation cell and som frondend static img path changed
> Incubation File Changed

- Frontend/src/Components/Top_Nav_Bar/About Us/Trust.jsx
- Frontend/src/Components/Top_Nav_Bar/Academics/Department.jsx
- Frontend/src/Components/Top_Nav_Bar/Academics/Programmes.jsx
- Frontend/src/Components/Top_Nav_Bar/Exams/Regulation.jsx
Integration for regulation and all dept id set successfully
> all dept id set

- Frontend/src/Components/Top_Nav_Bar/Academics/HeadDepartment.module.css
- Frontend/src/Components/Top_Nav_Bar/Academics/sections/HeadDepartment.jsx
- Frontend/src/Components/Top_Nav_Bar/Academics/sections/VisionMission.css
- Frontend/src/Components/Top_Nav_Bar/Exams/Regulation.jsx
- Frontend/src/Components/Top_Nav_Bar/Exams/Syllabus.jsx
Minor css change in department Page , Regulation, curiculum and syllabus,
> Minor css change in department Page

- Frontend/src/Components/Second_Nav_Bar/Grievences.jsx
- Frontend/src/Components/Second_Nav_Bar/Other-Facilities.jsx
> tinkering in helpdesk and OF

- Frontend/src/Components/Top_Nav_Bar/About Us/Trust.css
- Frontend/src/Components/Top_Nav_Bar/About Us/Trust.jsx
- Frontend/src/Components/Top_Nav_Bar/Academics/Programmes.jsx
- Frontend/src/Components/Top_Nav_Bar/Administration/Dean.css
- Frontend/src/Components/Top_Nav_Bar/Administration/admin.css
- Frontend/src/Components/Top_Nav_Bar/Administration/admin.jsx
- Frontend/src/Components/Top_Nav_Bar/Administration/dean.jsx
Image style fix in dean and admin page, faculty profile page redirect from dean page, Programmes alpha order set
> Image style fix in dean and admin page

- Frontend/src/Components/LoadComp.jsx
- Frontend/src/Components/Top_Nav_Bar/About Us/AbtUs.jsx
- Frontend/src/Components/Top_Nav_Bar/About Us/Management.jsx
- Frontend/src/Components/Top_Nav_Bar/About Us/Trust.jsx
- Frontend/src/Components/Top_Nav_Bar/Academics/DepartmentPage.jsx
- Frontend/src/Components/Top_Nav_Bar/Academics/Programmes.jsx
- Frontend/src/Components/Top_Nav_Bar/Academics/sections/CurriculamPage.jsx
- Frontend/src/Components/Top_Nav_Bar/Academics/sections/Faculties.jsx
- Frontend/src/Components/Top_Nav_Bar/Academics/sections/HeadDepartment.jsx
- Frontend/src/Components/Top_Nav_Bar/Academics/sections/Infrastructure.jsx
- Frontend/src/Components/Top_Nav_Bar/Academics/sections/RD.jsx
- Frontend/src/Components/Top_Nav_Bar/Academics/sections/Student_activities.jsx
- Frontend/src/Components/Top_Nav_Bar/Academics/sections/VisionMission.jsx
- Frontend/src/Components/Top_Nav_Bar/Academics/sections/activities.jsx
- Frontend/src/Components/Top_Nav_Bar/Academics/sections/mou.jsx
- Frontend/src/Components/Top_Nav_Bar/Academics/sections/newsletter.jsx
- Frontend/src/Components/Top_Nav_Bar/Administration/admin.css
- Frontend/src/Components/Top_Nav_Bar/Placements/PlacementTeam.css
- Frontend/src/Components/Top_Nav_Bar/Placements/PlacementTeam.jsx
> Department Loading screen fit

- Frontend/src/Components/Second_Nav_Bar/library/Libraryinfra.jsx
services,digital library&E-resources,OPAC,activities,downloads
> library page

- Frontend/src/Components/Second_Nav_Bar/sports/SportsPage.jsx
- Frontend/src/Components/Second_Nav_Bar/sports/Sportshod.css
- Frontend/src/Components/Second_Nav_Bar/sports/sports_faculties.jsx
> sports_faculties

- Backend/Main/controllers/departmentController.js
- Frontend/src/Components/Top_Nav_Bar/Academics/sections/RD.jsx
Research data page fetching fix for the new updation of the json structure
> Research data fix

- Frontend/src/Components/Top_Nav_Bar/Academics/sections/Conference.css
- Frontend/src/Components/Top_Nav_Bar/Academics/sections/ImageCard.jsx
- Frontend/src/Components/Top_Nav_Bar/Academics/sections/Infrastructure.jsx
- Frontend/src/Components/Top_Nav_Bar/Academics/sections/VisionMission.css
- Frontend/src/Components/Top_Nav_Bar/Academics/sections/VisionMission.jsx
- Frontend/src/Components/Top_Nav_Bar/Academics/sections/infrastructure.css
imagecard, infrastructure vision and mission page card and some other changes
> pages and card changes

- Frontend/src/Components/Second_Nav_Bar/NCC/NCC_ARMY.jsx
- Frontend/src/Components/Second_Nav_Bar/NCC/NCC_NAVY.jsx
- Frontend/src/Components/Second_Nav_Bar/Other-Facilities.jsx
other facilities image path changed
> Other facilities,NCC army,NCC navy

- Frontend/src/Components/Second_Nav_Bar/NSS/NSSCarousel.css
- Frontend/src/Components/Second_Nav_Bar/YRC.css
- Frontend/src/Components/Second_Nav_Bar/YRC.jsx
1. YRC recent events slide effect
2. YRC coordintaors tile effect done
> YRC Recent events, YRC teams and coordinators

- Frontend/src/Components/Second_Nav_Bar/YRC.css
- Frontend/src/Components/Second_Nav_Bar/YRC.jsx
1.YRC teams & coordinators tile effect done
> YRC teams and coordinators

- Frontend/src/Components/Second_Nav_Bar/NSS/NSSCoordinatiors.jsx
- Frontend/src/Components/Second_Nav_Bar/NSS/NSSCoordinators.css
- Frontend/src/Components/Top_Nav_Bar/Admission/ADM-M.E.jsx
- Frontend/src/Components/Top_Nav_Bar/Admission/ADM-MBA.jsx
- Frontend/src/Components/Top_Nav_Bar/Admission/UgAdmission.jsx
NSS-TEAM&COORDINATORS change, admission(top-nav-bar)-text content change
> NSS,Admission

- Frontend/src/Components/Second_Nav_Bar/Other-Facilities.css
- Frontend/src/Components/Second_Nav_Bar/Other-Facilities.jsx
buttton fixed ,fixing image name
> other facilities

- Frontend/src/Components/Second_Nav_Bar/IQAC.css
- Frontend/src/Components/Second_Nav_Bar/IQAC.jsx
- Frontend/src/Components/Second_Nav_Bar/NCC/NCC_ARMY.css
- Frontend/src/Components/Second_Nav_Bar/NSS/NotificationBox.css
- Frontend/src/Components/Second_Nav_Bar/YRC.css
- Frontend/src/Components/Second_Nav_Bar/YRC.jsx
- Frontend/src/Components/Second_Nav_Bar/iic.css
- Frontend/src/Components/Top_Nav_Bar/Admission/ADM-M.E.css
- Frontend/src/Components/Top_Nav_Bar/Admission/PhdAdmission.css
- Frontend/src/Components/Top_Nav_Bar/Admission/UgAdmission.css
iic,iqac,yrc,addmission,nss,ncc,yrc
> mobile responsive fix

- Frontend/src/Components/Top_Nav_Bar/Academics/Programmes.css
- Frontend/src/Components/Top_Nav_Bar/Academics/dapartment1.css
- Frontend/src/Components/Top_Nav_Bar/Academics/sections/CurriculamPage.jsx
- Frontend/src/Components/Top_Nav_Bar/Academics/sections/CurriculumPage.css
- Frontend/src/Components/Top_Nav_Bar/Academics/sections/Facultyprofile.css
- Frontend/src/Components/Top_Nav_Bar/Academics/sections/Facultyprofile.jsx
- Frontend/src/Components/Top_Nav_Bar/Academics/sections/RD.css
- Frontend/src/Components/Top_Nav_Bar/Academics/sections/Student_activities.css
- Frontend/src/Components/Top_Nav_Bar/Academics/sections/VisionMission.css
- Frontend/src/Components/Top_Nav_Bar/Academics/sections/infrastructure.css
- Frontend/src/Components/Top_Nav_Bar/Research/reseach details.jsx
- Frontend/src/Components/Top_Nav_Bar/Research/researchdetails.css
- Frontend/tailwind.config.js
Academics media query and font size fixed,research detail jsx and css new created and code work
> Academics,reseach deatails

- Frontend/src/Components/Top_Nav_Bar/About Us/AbtUs.css
- Frontend/src/Components/Top_Nav_Bar/About Us/AbtUs.jsx
- Frontend/src/Components/Top_Nav_Bar/About Us/Management.css
- Frontend/src/Components/Top_Nav_Bar/About Us/Management.jsx
- Frontend/src/Components/Top_Nav_Bar/Academics/sections/VisionMission.jsx
- Frontend/src/Components/Top_Nav_Bar/Research/Academicresearch.css
- Frontend/src/Components/Top_Nav_Bar/Research/Academicresearch.jsx
About us, Management, Vision mission CSS mobile view Academics research
> Aboutus, Research Page

- Frontend/src/Components/Second_Nav_Bar/Hostel/AdmissionHost.css
- Frontend/src/Components/Second_Nav_Bar/Hostel/InfoHostel.css
- Frontend/src/Components/Second_Nav_Bar/Hostel/LoginHost.css
- Frontend/src/Components/Second_Nav_Bar/Hostel/aboutHost.css
- Frontend/src/Components/Second_Nav_Bar/Hostel/aboutHost.jsx
- Frontend/src/Components/Second_Nav_Bar/Hostel/hostelfacilities.css
- Frontend/src/Components/Second_Nav_Bar/Hostel/warden.css
- Frontend/src/Components/Second_Nav_Bar/NCC/NCC_ARMY comps/NCCACarousel.css
- Frontend/src/Components/Second_Nav_Bar/NCC/NCC_ARMY comps/NCCAMenbers.css
- Frontend/src/Components/Second_Nav_Bar/NCC/NCC_ARMY comps/NCCAtable.css
- Frontend/src/Components/Second_Nav_Bar/NCC/NCC_ARMY comps/corouselarmy.css
- Frontend/src/Components/Second_Nav_Bar/NCC/NCC_ARMY.css
- Frontend/src/Components/Second_Nav_Bar/NCC/NCC_MAIN.css
- Frontend/src/Components/Second_Nav_Bar/NCC/NCC_NAVY.css
- Frontend/src/Components/Second_Nav_Bar/Transport/Transport.jsx
- Frontend/src/Components/Second_Nav_Bar/sports/SportsInfra.css
- Frontend/src/Components/Second_Nav_Bar/sports/SportsInfra.jsx
- Frontend/src/Components/Second_Nav_Bar/sports/SportsPage.css
sports infra mobile view fix and css files font change
> sports,font(css)

- Frontend/src/Components/Second_Nav_Bar/Alumni.css
- Frontend/src/Components/Second_Nav_Bar/IQAC.css
- Frontend/src/Components/Second_Nav_Bar/IQAC.jsx
- Frontend/src/Components/Second_Nav_Bar/NBA_F.css
- Frontend/src/Components/Second_Nav_Bar/NCC/NCC_ARMY.css
- Frontend/src/Components/Second_Nav_Bar/NCC/NCC_ARMY.jsx
- Frontend/src/Components/Second_Nav_Bar/NSS/NSSCotent.css
- Frontend/src/Components/Second_Nav_Bar/NSS/NotificationBox.css
- Frontend/src/Components/Second_Nav_Bar/YRC.css
- Frontend/src/Components/Second_Nav_Bar/iic.jsx
- Frontend/src/Components/Second_Nav_Bar/naac.css
- Frontend/src/Components/Second_Nav_Bar/naac.jsx
- Frontend/src/Components/Second_Nav_Bar/nirf.css
- Frontend/tailwind.config.js
alumi,iic,iqac,naac,nba,ncc,nirf,notificationbox,nss,yrc
> font size change

- Frontend/src/App.js
- Frontend/src/Components/Top_Nav_Bar/Research/Academicresearch.css
- Frontend/src/Components/Top_Nav_Bar/Research/Academicresearch.jsx
- Frontend/src/Components/Top_Nav_Bar/Research/Bookpublication.css
- Frontend/src/Components/Top_Nav_Bar/Research/Bookpublication.jsx
- Frontend/src/Components/Top_Nav_Bar/Research/Researchtable.css
- Frontend/src/Components/Top_Nav_Bar/Research/Researchtable.jsx
researchtable , add the banner to acadamic , bookpublication
> researchtable

- Frontend/src/Components/Landing Comp/SideBar.jsx
- Frontend/src/Components/Top_Nav_Bar/Research/Academicresearch.jsx
- Frontend/src/Components/Top_Nav_Bar/Research/Researchtable.jsx
little changes in academic research
> academic research

- Frontend/src/Components/Top_Nav_Bar/Research/Conferencepublication.jsx
- Frontend/src/Components/Top_Nav_Bar/Research/Journalpublication.css
- Frontend/src/Components/Top_Nav_Bar/Research/Journalpublication.jsx
- Frontend/src/Components/Top_Nav_Bar/Research/reseach details.jsx
- Frontend/src/Components/Top_Nav_Bar/Research/researchdetails.css
Research Page integration completed for journal publication
> Research Page

- Frontend/package.json
- Frontend/src/Components/Second_Nav_Bar/IQAC.css
- Frontend/src/Components/Second_Nav_Bar/Incub.css
- Frontend/src/Components/Second_Nav_Bar/NSS/NSSContent.jsx
- Frontend/src/Components/Second_Nav_Bar/NSS/NotificationBox.css
- Frontend/src/Components/Second_Nav_Bar/Transport/Transport.jsx
- Frontend/src/Components/Second_Nav_Bar/YRC.css
- Frontend/src/Components/Second_Nav_Bar/YRC.jsx
IQAC, YRC, Transport , notification
> Praveen UI Change

- Frontend/src/Components/Second_Nav_Bar/IQAC.css
- Frontend/src/Components/Second_Nav_Bar/YRC.css
- Frontend/src/Components/Second_Nav_Bar/YRC.jsx
- Frontend/src/Components/Top_Nav_Bar/Academics/Programmes.css
- Frontend/src/Components/Top_Nav_Bar/Academics/Programmes.jsx
- Frontend/src/Components/Top_Nav_Bar/Academics/dapartment1.css
- Frontend/src/Components/Top_Nav_Bar/Academics/sections/Faculties.module.css
- Frontend/src/Components/Top_Nav_Bar/Academics/sections/HeadDepartment.jsx
- Frontend/src/Components/Top_Nav_Bar/Academics/sections/ImageCard.jsx
- Frontend/src/Components/Top_Nav_Bar/Academics/sections/VisionMission.css
- Frontend/src/Components/Top_Nav_Bar/Administration/Dean.css
- Frontend/src/Components/Top_Nav_Bar/Administration/Princ.jsx
- Frontend/src/Components/Top_Nav_Bar/Administration/admin.jsx
- Frontend/src/Components/Top_Nav_Bar/Research/Researchtable.css
- Frontend/src/Components/Top_Nav_Bar/Research/Researchtable.jsx
ui change in some pages eg..IQAC and other
> modifications

- Frontend/src/Components/Banner.css
- Frontend/src/Components/Banner.jsx
- Frontend/src/Components/Second_Nav_Bar/IQAC.css
- Frontend/src/Components/Second_Nav_Bar/NBA_F.css
- Frontend/src/Components/Second_Nav_Bar/NBA_F.jsx
- Frontend/src/Components/Top_Nav_Bar/Admission/UgAdmission.jsx
- Frontend/src/Components/Top_Nav_Bar/Exams/Forms.css
- Frontend/src/Components/Top_Nav_Bar/Exams/forms.jsx
NBA
Ugadmission
IQAC
Exams-Downloads
Banner
> Responsive

- Frontend/src/Components/Second_Nav_Bar/Alumni.jsx
- Frontend/src/Components/Second_Nav_Bar/InCub.jsx
- Frontend/src/Components/Second_Nav_Bar/iic.css
- Frontend/src/Components/Second_Nav_Bar/iic.jsx
makeing an user interface set network issue set
> user data and network

- Frontend/src/Components/Second_Nav_Bar/IQAC.jsx
- Frontend/src/Components/Second_Nav_Bar/NBA_F.jsx
- Frontend/src/Components/Second_Nav_Bar/naac.jsx
- Frontend/src/Components/Second_Nav_Bar/nirf.jsx
Loading screen for offline set for iqac , naac, nba, nief
> Loading For offline

- Frontend/src/Components/Landing Comp/Head.jsx
- Frontend/src/Components/Second_Nav_Bar/IQAC.jsx
- Frontend/src/Components/Second_Nav_Bar/InCub.jsx
- Frontend/src/Components/Second_Nav_Bar/iic.jsx
- Frontend/src/Components/Top_Nav_Bar/Academics/sections/Faculties.module.css
- Frontend/src/Components/Top_Nav_Bar/Academics/sections/ImageCard.jsx
- Frontend/src/Components/Top_Nav_Bar/Research/Academicresearch.jsx
- Frontend/src/Components/Top_Nav_Bar/Research/Sponseredresearch.jsx
- Frontend/src/Landing.jsx
Principle Changes for acadamic page, iqac, incubation cell, iic
> Principle Changes Ajith

- Backend/Main/controllers/coeController.js
> COE to coe

- Backend/package-lock.json
- Frontend/src/App.js
- Frontend/src/Components/ScrollUp.css
- Frontend/src/Components/ScrollUp.jsx
- Frontend/src/Components/Top_Nav_Bar/About Us/AbtUs.jsx
- Frontend/src/Landing.jsx
> scroll up set

- Frontend/src/Components/Landing Comp/Head.jsx
- Frontend/src/Components/Second_Nav_Bar/IIC/IICContect.jsx
- Frontend/src/Components/Second_Nav_Bar/IIC/KamalaBar.jsx
- Frontend/src/Components/Second_Nav_Bar/iic.jsx
active button setted , border changed
> missing changes setted

- Frontend/src/Components/Top_Nav_Bar/Academics/sections/Student_activities.css
- Frontend/src/Components/Top_Nav_Bar/Academics/sections/Student_activities.jsx
Student Activities image link set successfully
> Student Activities

- Frontend/src/Components/ScrollUp.css
- Frontend/src/Components/ScrollUp.jsx
- Frontend/src/Components/Top_Nav_Bar/Administration/admin.css
> enquire, admin

- Frontend/src/Components/Top_Nav_Bar/About Us/AbtUs.jsx
- Frontend/src/Components/Top_Nav_Bar/About Us/Management.css
- Frontend/src/Components/Top_Nav_Bar/About Us/Management.jsx
- Frontend/src/Header.jsx
> mac changes

- Backend/docs/DEPT_DATA/013.json
added department activities for the year
-2025
img.no - 11, 12
-2024
img.no - 8, 9, 10
-2023
img.no - 5, 13, 14, 15, 16, 17, 18, 19, 20
-2022
img.no - 21
> updated 013.json dept activities
